{% set name = "opentelemetry-distro" %}
{% set version = "0.47b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_distro-{{ version }}.tar.gz
  sha256: 715615724bd5c528a2433c0caeb373e4581f8dc7b4bc270179407a1cca0ad99e

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  number: 0
  skip: True # [py<38]

requirements:
  host:
    - python
    - pip
    - hatchling
    - setuptools
    - wheel
  run:
    - python
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-sdk >=1.13,<2.dev0

test:
  imports:
    - opentelemetry.distro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-distro
  summary: OpenTelemetry Python Distro
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-distro
  dev_url: https://pypi.org/project/opentelemetry-distro/


extra:
  recipe-maintainers:
    - rxm7706
    - goatmale