{% set name = "opentelemetry-distro" %}
{% set version = "0.59b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: a72703a514e1773d35d1ec01489a5fd1f1e7ce92e93cf459ba60f85b880d0099

build:
  number: 0
  skip: True # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-instrumentation =={{ version }}
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-sdk >=1.13,<2.dev0
  run_constrained:
    - opentelemetry-exporter-otlp ==1.38.0

test:
  source_files:
    - tests
  imports:
    - opentelemetry.distro
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-distro
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: OpenTelemetry Python Distro
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/opentelemetry-distro
  dev_url: https://pypi.org/project/opentelemetry-distro


extra:
  recipe-maintainers:
    - rxm7706
    - goatmale
